# Generated by Django 6.0.4 on 2026-04-17 23:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Jacksonville', 'Jacksonville'), ('Miami', 'Miami'), ('Orlando', 'Orlando'), ('Tampa', 'Tampa'), ('St. Petersburg', 'St. Petersburg')], max_length=50)),
                ('date', models.DateField()),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('sunrise', models.DateTimeField(blank=True, null=True)),
                ('sunset', models.DateTimeField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('precip_probability', models.FloatField(blank=True, null=True)),
                ('rain_sum', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('Not Rated', 'Not Rated'), ('Approved', 'Approved'), ('TV-PG', 'TV-PG'), ('Unrated', 'Unrated'), ('X', 'X'), ('TV-MA', 'TV-MA'), ('TV-14', 'TV-14')], max_length=10)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2030)])),
                ('released', models.CharField(blank=True, max_length=100)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('votes', models.PositiveIntegerField()),
                ('director', models.CharField(blank=True, max_length=255)),
                ('writer', models.CharField(blank=True, max_length=255)),
                ('star', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('gross', models.FloatField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.genre')),
            ],
            options={
                'ordering': ['-year', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
    ]
